# -*- coding: utf-8 -*-
from scripts import i18n_mh as mh

mh.TPL = "src/web/templates/help.html"
mh.insert_keys(
    {
        "hp_s000": "帮助",
        "hp_s001": "常用指令",
        "hp_s002": "帮助 & 指令参考",
        "hp_s003": "仅显示常用指令。",
        "hp_s004": "切换完整模式",
        "hp_s005": "查看全部指令。",
        "hp_s006": "客服培训演示",
        "hp_s007": "（全屏幻灯片，含知识库与人工转接流程）",
        "hp_s008": "打开培训演示",
        "hp_s009": "搜索指令关键词…",
        "hp_s010": "找不到匹配的指令",
        "hp_s011": "指令",
        "hp_s012": "说明",
        "hp_s013": "示例",
        "hp_s014": "权限",
        "hp_s015": "复制指令",
        "hp_role_all": "所有人",
        "hp_js_copied": "已复制：",
        "hp_sec_scripts": "话术管理",
        "hp_cmd_setgreeting": "设置问候语",
        "hp_ex_setgreeting": "/setgreeting 你好！",
        "hp_cmd_setrate": "设置通道费率",
        "hp_ex_setrate": "/setrate ch1 6.85",
        "hp_cmd_status": "查看当前通道状态",
        "hp_ex_status": "/status",
        "hp_cmd_help": "显示帮助信息",
        "hp_ex_help": "/help",
    },
    {
        "hp_s000": "Help",
        "hp_s001": "Common commands",
        "hp_s002": "Help & command reference",
        "hp_s003": "Showing common commands only. ",
        "hp_s004": "Switch to full mode",
        "hp_s005": " to browse all commands.",
        "hp_s006": "Agent training demo",
        "hp_s007": " (fullscreen slides: knowledge base & handoff flow)",
        "hp_s008": "Open training demo",
        "hp_s009": "Search command keywords…",
        "hp_s010": "No matching commands",
        "hp_s011": "Command",
        "hp_s012": "Description",
        "hp_s013": "Example",
        "hp_s014": "Access",
        "hp_s015": "Copy command",
        "hp_role_all": "Everyone",
        "hp_js_copied": "Copied: ",
        "hp_sec_scripts": "Script management",
        "hp_cmd_setgreeting": "Set greeting message",
        "hp_ex_setgreeting": "/setgreeting Hello!",
        "hp_cmd_setrate": "Set channel rate",
        "hp_ex_setrate": "/setrate ch1 6.85",
        "hp_cmd_status": "View current channel status",
        "hp_ex_status": "/status",
        "hp_cmd_help": "Show help information",
        "hp_ex_help": "/help",
    },
)
print("help keys inserted")
